model: mlx-community/DeepHermes-3-Llama-3-8B-Preview-bf16
data: data/qa/mlx
adapter_path: data/models/DeepHermes-3-Llama-3-8B-Preview-bf16-lora-gs
#resume_adapter_file: data/models/gemma-3-4b-it-bf16-lora/adapters.safetensors
train: true

seed: 17
grad_checkpoint: true

# More conservative defaults for BF16 on 24 GB
batch_size: 2
max_seq_length: 1024
iters: 200
learning_rate: 5e-5
save_every: 100

lora_parameters:
  rank: 64
  alpha: 128
  dropout: 0.05
  scale: 2.0
lora_layers: 32